"""M8a — non-circle synthetic shapes, Qwen2.5-VL-7B label-free arm.

Companion to `m8a_qwen.py`. Single `_nolabel` arm for paired-delta
visual-saturation testing: paired-delta(role) = PMR(role) − PMR(_nolabel)
should shrink toward 0 (or sign-mix) on shapes whose vision-encoder
representations are saturated.

Reuses the stimuli generated by `m8a_qwen.py` via `--stimulus-dir`.
"""

from __future__ import annotations

from physical_mode.config import EvalConfig, FactorialSpec

CONFIG = EvalConfig(
    run_name="m8a_qwen_label_free",
    model_id="Qwen/Qwen2.5-VL-7B-Instruct",
    torch_dtype="bfloat16",
    max_new_tokens=96,
    temperature=0.7,
    top_p=0.95,
    factorial=FactorialSpec(
        shapes=("circle", "square", "triangle", "hexagon", "polygon"),
        object_levels=("line", "filled", "shaded", "textured"),
        bg_levels=("blank", "ground"),
        cue_levels=("none", "both"),
        event_templates=("fall",),
        seeds_per_cell=5,
    ),
    labels=("_nolabel",),
    prompt_variants=("open_no_label",),
    capture_lm_layers=None,
    capture_lm_attentions=False,
    random_seed=42,
)
