"""M8a — non-circle synthetic shapes, LLaVA-1.5-7B run.

Cross-model companion to `m8a_qwen.py`. Reuses the stimuli generated by
that config (via `--stimulus-dir`) so paired-delta and per-shape
comparisons across models are exactly aligned at the pixel level.

See `m8a_qwen.py` for factorial design and label-role dispatch.

Forced-choice is excluded (LLaVA's "A" lock from M6 r1 carries over).
Open-prompt sampling settings match the M6 r1 cross-model run.
"""

from __future__ import annotations

from physical_mode.config import EvalConfig, FactorialSpec

CONFIG = EvalConfig(
    run_name="m8a_llava",
    model_id="llava-hf/llava-1.5-7b-hf",
    torch_dtype="bfloat16",
    max_new_tokens=96,
    temperature=0.7,
    top_p=0.95,
    factorial=FactorialSpec(
        shapes=("circle", "square", "triangle", "hexagon", "polygon"),
        object_levels=("line", "filled", "shaded", "textured"),
        bg_levels=("blank", "ground"),
        cue_levels=("none", "both"),
        event_templates=("fall",),
        seeds_per_cell=5,
    ),
    labels=("physical", "abstract", "exotic"),
    prompt_variants=("open",),
    capture_lm_layers=None,
    capture_lm_attentions=False,
    random_seed=42,
)
