"""M8d — non-ball physical-object categories, Qwen2.5-VL-7B label-free arm.

Companion to `m8d_qwen.py`. Single `_nolabel` arm for paired-delta
visual-saturation testing across categories: paired-delta(role) =
PMR(role) − PMR(_nolabel) tracks both the per-category language-prior
contribution and the cross-category encoder-saturation signature.

Reuses the stimuli generated by `m8d_qwen.py` via `--stimulus-dir`.
"""

from __future__ import annotations

from physical_mode.config import EvalConfig, FactorialSpec

CONFIG = EvalConfig(
    run_name="m8d_qwen_label_free",
    model_id="Qwen/Qwen2.5-VL-7B-Instruct",
    torch_dtype="bfloat16",
    max_new_tokens=96,
    temperature=0.7,
    top_p=0.95,
    factorial=FactorialSpec(
        shapes=("car", "person", "bird"),
        object_levels=("line", "filled", "shaded", "textured"),
        bg_levels=("blank", "ground"),
        cue_levels=("none", "both"),
        event_templates=("fall", "horizontal"),
        seeds_per_cell=5,
    ),
    labels=("_nolabel",),
    prompt_variants=("open_no_label",),
    capture_lm_layers=None,
    capture_lm_attentions=False,
    random_seed=42,
)
