"""M8d — non-ball physical-object categories, LLaVA-1.5-7B labeled run.

Cross-model companion to `m8d_qwen.py`. Reuses the stimuli generated by
the Qwen run (via `--stimulus-dir`) so paired-delta and per-category
comparisons across models are pixel-aligned.

See `m8d_qwen.py` for factorial design and label-role dispatch. Forced-
choice excluded (LLaVA's "A" lock from M6 r1 carries over).
"""

from __future__ import annotations

from physical_mode.config import EvalConfig, FactorialSpec

CONFIG = EvalConfig(
    run_name="m8d_llava",
    model_id="llava-hf/llava-1.5-7b-hf",
    torch_dtype="bfloat16",
    max_new_tokens=96,
    temperature=0.7,
    top_p=0.95,
    factorial=FactorialSpec(
        shapes=("car", "person", "bird"),
        object_levels=("line", "filled", "shaded", "textured"),
        bg_levels=("blank", "ground"),
        cue_levels=("none", "both"),
        event_templates=("fall", "horizontal"),
        seeds_per_cell=5,
    ),
    labels=("physical", "abstract", "exotic"),
    prompt_variants=("open",),
    capture_lm_layers=None,
    capture_lm_attentions=False,
    random_seed=42,
)
